
FROM node:18 as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Production stage
FROM nginx:stable-alpine as production-stage

# Copy the build output to replace the default Nginx contents.
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Copy custom Nginx configuration
COPY nginx.conf ./

EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]